language: ruby
rvm:
- 2.5.3
notifications:
  email: false
  slack:
    secure: b8IARHpf2EXWfXKBjBxvghrJG4LUruICVHA54oggNT1ZsTRKdQl9vRBDMO4sxAXGrfG/mYJ5GqqwTpsvVTVdIcA02ZOFc1G63D8k8KZiLwVPXmXmtq+xcpmXaNZH6I2yb62AaILpLCbNATXOYrCVhBr8BFcHKY0LJi9LG9tZa/n2Qg4DVtX+e8yr4QbCLlJoYKOF+43BS5Y+v5RmSyJ7L00qkFwahwQmWEHf+1fqt/4NttejGz7Lq/BxONmwNMYdYSpY5Pg3RJ6L4vONOBzxe5qi3uwoPqvbkCr9c9VL3adkiqRa/1Q5hsfnHwh1uUvr1/25F2ReKM0vq9f8xuCgiN0QONdbaUtzT4VsdXYaS7MICy+6c7w6E0RHVdSy2j7TyRVmLcsbzwxbBXjhhXVqT9VeF4cyWR7FZRWCV23eB1WVavYHbv4sB4CqMpu+E9nIPb635ZDbVts8R8aN7Q2lXu9zSFDDsP7Ts2XVJhZB8iqITSzpab2xptA6zuuv0TC9xr3fADZfc296lg4IxGOL0Lzmjk7YFK8lXwwR3G/H2WpEnyg4JkTmKITcwUU8oihPCY0bgnH62KsmbaT4hF7VWIv9XWyJu5uzpPmD9b57yV5vHODUTL3ea+9gOuKVgC7gV0Rdm93vhURQ1aLJbI8RyZDTcAkCmFCD/xoH/EBCFJ4=
