service: ba-sing-se

provider:
  name: aws
  region: eu-west-2
  runtime: nodejs10.x
  stage: prod

functions:
  nuxt:
    handler: index.nuxt
    events:
      - http: ANY /
      - http: ANY /{proxy+}

plugins:
  - serverless-apigw-binary

custom:
  apigwBinary:
    types:
      - '*/*'
