version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/ruby:2.5.3-node
    working_directory: ~/ba-sing-se
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/ba-sing-se
  build:
    docker:
      - image: circleci/ruby:2.5.3-node
    working_directory: ~/ba-sing-se
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: |
          gem update --system
          gem install bundler
          bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
          paths:
            - ~/ba-sing-se/vendor/bundle
  tests:
    docker:
      - image: circleci/ruby:2.5.3-node
      # - image: circleci/postgres:latest
    working_directory: ~/ba-sing-se
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run: |
          gem update --system
          gem install bundler
          bundle --path vendor/bundle
      # - run: bundle exec rake db:create db:schema:load
      - run:
          name: Run tests
          command: bundle exec rake
  deploy:
    docker:
      - image: circleci/ruby:2.5.3-node
    working_directory: ~/ba-sing-se
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ checksum "Gemfile.lock" }}
      - run:
          name: Deploy
          command: |
            gem update --system
            gem install bundler
            bundle install --jobs=4 --retry=3 --path vendor/bundle
            gem install jets
            sudo apt-get update && sudo apt-get install rsync
            bundle exec jets deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - checkout_code
      - build:
          requires:
            - checkout_code
      - tests:
          requires:
            - build
      - deploy:
          requires:
            - tests
          filters:
            branches:
              only: master
